Sprint 2
VnGrigoreva/middle.messenger.praktikum.yandex pull request #2
Opened 2022-02-01 20:22 UTC by VnGrigoreva

2022-02-02 21:36 UTC, DmitryKhitrin requested changes
Привет, спасибо за отличную работу - классная идея с типизацией пропсов + отличная работа с валидацией) В комментариях описал некоторые вопросы, которые у меня возникли, посмотрите на них пожалуйста

2022-02-02 21:36 UTC, DmitryKhitrin commented on .eslintignore
> +/server
Для git важно, что бы файл заканчивался [пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-02-02 21:36 UTC, DmitryKhitrin commented on .stylelintrc.json
> +}
[EOF](https://eslint.org/docs/rules/eol-last)

2022-02-02 21:36 UTC, DmitryKhitrin commented on server/index.js
> +app.get('/', function (request, response) {
Для функций колбеков, обычно используются стрелочный функции
```suggestion
app.get('/', (request, response) => {
```

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Block/Block.ts
> +  init = 'init',
Ключи в enum принято именовать с заглавной буквы) [Пример из официально документации TS](https://www.typescriptlang.org/docs/handbook/enums.html)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Block/Block.ts
> +export class Block<TProps extends PropsType = any> {
Отличное решение!)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Block/Block.ts
> +  _registerEvents(eventBus: EventBus) {
Для приватный функций классов, есть ключевое слово [private](https://www.typescriptlang.org/docs/handbook/classes.html)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Block/Block.ts
> +    // const result = this._createDocumentElement(template);
Лучше не оставлять вот так закомментированный код, уже через пару недель забывается что это и зачем оно тут( Так что либо писать комментарий, либо удалять совсем)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Block/Block.ts
> +  _createDocumentElement() {
Как будто эта функция не относится к базовому блоку. Он отвечает за жизненный цикл и только принимает верстку на вход

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/ErrorPage/ErrorPage.ts
> +      ...this.props,
Спредить пропсы не очень хорошая практика, так гораздо сложнее потом разбираться, что откуда прилетело(

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/ErrorPage/template.ts
> +`
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Input/Input.ts
> +  error?: string;
Хорошая практика описывать сначала обязательные поля, потом опциональные

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/components/Link/link.scss
> +    // margin-top: 10px;
Закомментированный код стоит удалять

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/HTTPTransport.ts
> +        // @ts-ignore
Зачем тут ts-ignore?

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/HTTPTransport.ts
> +        resolve(xhr);
Тут сразу можно проверить статус ответа и если он условно не 200, бросить reject

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/eventBus.ts
> +  private listeners: {[key: string]: CallbackType[]};
Для таких типов есть хелпер [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html) `Record<string, CallbackType[]>`

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/eventBus.ts
> +		if (!this.listeners[event]) {
Тут кажется форматирование поехало

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/eventBus.ts
> +	emit(event: string, ...args: unknown[]) {
Тут тоже проблемы с форматированием, такие проблемы хорошо решает [Prettier](https://prettier.io/)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/eventBus.ts
> +}
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/validateService.ts
> +  return email.match(/^[\w]{1}[\w-\.]*@[\w-]+\.[a-z]{2,4}$/i)
Люди миллионы лет валидируют email и всеохватывающая регулярка выглядит примерно [так](https://emailregex.com/). Если что, ее можно позаимствовать, с указанием источника)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/validateService.ts
> +};
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/validateService.ts
> +export const validateMessage= (message: string): string | undefined => {
```suggestion
export const validateMessage = (message: string): string | undefined => {
```

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/modules/validateService.ts
> +  return login.match(/^[\w-]{3,20}$/) && isNaN(+login)
Тут кажется немного странным решение при корректном инпуте возвращать undefined. Думаю лучше возвращать объект, у которого будут поля isValid и errorMessage, так немного больше кода, зато гораздо нагляднее)

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/pages/auth/Login/Login.ts
> +      if (login && !Mediator.Instance.validateLogin(login as string) && password) {
Лучше не кастить типы таким образом, получается не очень безопасно. В данном случае я бы предложил:

`String(login)`

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/pages/auth/Login/template.ts
> +`
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/pages/auth/Registration/Registration.ts
> +      if (email && !Mediator.Instance.validateEmail(email as string)
А зачем мы на маунте компонента проверяем все поля?

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/pages/profile/PasswordEditing/PasswordEditing.ts
> +  newPassword ='';
```suggestion
  private newPassword: string  = '';
```

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/pages/profile/PasswordEditing/template.ts
> +`
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/types/global.d.ts
> +}
EOF

2022-02-02 21:36 UTC, DmitryKhitrin commented on src/utils/queryStringify.ts
> +export default function (data: {[key: string]: string} | undefined): string {
Будет удобней дать функции название)

2022-02-03 13:46 UTC, VnGrigoreva commented on src/pages/auth/Registration/Registration.ts
> +      if (email && !Mediator.Instance.validateEmail(email as string)
Там внутри cdm создавалась функция handleSubmit, которая вызывается на submit формы. По заданию валидацию на кнопку надо повторить. Создавалась и сразу в качестве пропса передавалась в компонент. Исправила, вынесла как метод компонента-класса.

2022-02-03 14:07 UTC, VnGrigoreva commented on src/pages/profile/PasswordEditing/PasswordEditing.ts
> +  newPassword ='';
[no-inferrable-types](https://typescript-eslint.io/rules/no-inferrable-types/ ) 
как приватное поле объявила

2022-02-04 08:20 UTC, DmitryKhitrin approved these changes

2022-02-16 08:56 UTC, merged